version: "3"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: squid
      POSTGRES_PASSWORD: postgres
    shm_size: 1gb
    ports:
      - "${DB_PORT}:5432"
      # command: ["postgres", "-c", "log_statement=all"]
    volumes:
      - ./data/db:/var/lib/postgresql/data

  processor:
    build:
      context: .
      target: processor
    environment:
      - DB_HOST=db
      - CHAIN_URL=${CHAIN_URL}
    depends_on:
      - db
    networks:
      - default
      - js

  query-node:
    build:
      context: .
      target: query-node
    environment:
      - DB_HOST=db
    depends_on:
      - db
    ports:
      - "127.0.0.1:${GQL_PORT}:4000"

networks:
  default: {}
  js:
    name: joystream_default
    external: true
